sudo: required
services:
    - docker


before_install:
  - docker build -t shanealeven/docker-react -f Dockerfile.dev .

script:
   - docker run shanealeven/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-302557873049"
  bucket_path: "docker-react"
  on:

    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"